In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv("house_price.txt")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [9]:
model.predict([[3000]])

array([587979.45205479])

In [11]:
import pickle

In [15]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [19]:
with open('model_pickle','rb') as file:
    mp=pickle.load(file)

In [20]:
mp.coef_

array([135.78767123])

In [21]:
mp.intercept_

180616.43835616432

In [22]:
mp.predict([[4000]])

array([723767.12328767])

# joblib

In [31]:
 import joblib

In [32]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [33]:
mj=joblib.load('model_joblib')

In [34]:
mj.coef_

array([135.78767123])

In [35]:
mj.predict([[4500]])

array([791660.95890411])